### ISSUE TITLE
Documentation of coordinate systems

### ISSUE THREAD

**Issue by stallinc** [USEPA/spsurvey#20]
Do coordinate systems need to be converted to albers prior to running grts function or are they automatically converted? The output of selected sites is in albers when decimal degrees was used in the data frame but I do not see reference to this in the documentation.

**Comment by mhweber** [comment]
Hi @stallinc  - in 4.1.3, if you use an sf object for grts, the CRS of your sf object is used for the CRS of the result - would have to see reprex of your design - are you looking at coordinate columns in the data frame of output or the geometry columns?  See examples below using NE_Lakes which should clarify.  Note that we are about to release 5.0 with many updates and it will require input to be an `sf` object.
`library(spsurvey)
data(NE_lakes)
NE_lakes <- st_transform(NE_lakes, 4269)
NE_lakes$xcoord <- st_coordinates(NE_lakes)[,1]
NE_lakes$ycoord <- st_coordinates(NE_lakes)[,2]
Equaldsgn <- list(None=list(panel=c(PanelOne=100), seltype="Equal"))
Equalsites <- grts(design=Equaldsgn,
                   DesignID="EQUAL",
                   type.frame="finite",
                   src.frame="sf.object",
                   sf.object=NE_lakes,
                   shapefile=FALSE)
head(Equalsites)

NE_lakes <- st_drop_geometry(NE_lakes)
Equaldsgn <- list(None=list(panel=c(PanelOne=100), seltype="Equal"))
Equalsites <- grts(design=Equaldsgn,
                   DesignID="EQUAL",
                   type.frame="finite",
                   src.frame="att.frame",
                   att.frame=NE_lakes,
                   xcoord = "xcoord",
                   ycoord = "ycoord",
                   shapefile=FALSE)
head(Equalsites)`
