### ISSUE TITLE
grts function should have methods for different input classes

### ISSUE THREAD

**Issue by jasonelaw** [USEPA/spsurvey#3]
I'm a longtime spsurvey user and I'm continually frustrated by using the interface to spsurvey. 
It seems like a single generic grts function grts(), with methods for:
- grts.data.frame()
- grts.character()
- grts.sf()
- grts.SpatialPointsDataFrame()
- grts.SpatialPolygonsDataFrame()
- grts.SpatialPointsDataFrame()

Would make the interface a lot easier. The generic interface could be as simple as:
grts(frame, design, stratum = ~ stratum, inclusion.prob = ~ mdcaty, options = list(startlev, maxlev, maxtry, shift.grid)

These arguments would be unnecessary with method dispatch: src.frame, in.shape, sf.object, sp.object, att.frame, xcoord, ycoord. Arguments shapefile and out.shape are better handled elsewhere. Giving the grts function side effects like this has always bothered me.

type.frame seems unnecessary too, but perhaps grts allows for overriding more complex geometries with simpler geometries (via st_centroid, or similar).

I realize that changing the grts function may be a nonstarter. Is it possible to implement with a different function name so that the old interface could be preserved?

I have forked the project and am very inclined and capable of helping with an effort like this. Please let me know how I can help improve spsurvey.

**Comment by tonyolsen** [comment]
Jason - appreciate the comment.  We are entirely rewriting spsurvey both the site selection and analysis parts.  We are using a private repository at this point to do that given that it is such a major change.  The new grts functions will only accept sf objects since sf is becoming the standard.  We will have separate functions for points, lines and polygons so the type.frame argument will disappear.  the output will be an sf object and user will have to write out their design - spsurvey will not have options to do that. Also eliminating very old C code and using sf functions to replace them. Including options for survey design to incorporate existing sites and/or to have minimum distance between sites.

**Comment by jasonelaw** [comment]
Any chance to make the repository public? Or can I help in any way? I'd like to give back...

**Comment by jasonelaw** [comment]
And @tonyolsen, you have a github account. :)

**Comment by mhweber** [comment]
@jasonelaw , you'll notice we now have a develop_5.0 branch where development on new version will be happening.  There will be other branches off this focusing temporarily on particular aspects of code.  As we get moving, you could put in pull requests or raise issues on this branch, but best to coordinate with @tonyolsen .

**Comment by tonyolsen** [comment]
Jason - I am working on grtspts branch of develop_5.0 branch.  One assumption is that input for sample frame will be sf.object only and only other required input is dsgn list.  Rest of arguments will all be optional. Have yet to totally finish the grtspts related functions but they are close. Note output will be sf.object as well.  Similar functions will be created for grtslin and grtsarea when we get to those.  When I have a finished grtspts set of functions Marc will merge the branch with develop_5.0.

**Comment by jasonelaw** [comment]
Thanks Tony! I will definitely take a look. I'm sure I will have a few questions. Do you have a roadmap for development that you guys are working on?

**Comment by jasonelaw** [comment]
I see a lot of large chunks of duplicative code: the main sample loops in grts for points, lines, and areas are almost identical. Even some of the differences in those loops aren't real differences: functions like mdmarea, mdmpts, mdmlin are duplicates except for variable names. I could easily do something simple like refactoring those functions to get started. If there is a roadmap, let me know so I can pitch in where you need it.

**Comment by tonyolsen** [comment]
Duplicated code removed and new functions replace old ones.
