### ISSUE TITLE
Feature Request Cat/Cont Analysis on message printing

### ISSUE THREAD

**Issue by sagesteppe** [USEPA/spsurvey#36]
Hi amazing work on the package! We use a few of these functions in reports we render to markdown, and I am wondering if it is at all possible to move transfer the usage of the 'cat' function to 'message'?

Essentially, we just  would like to hide a few of the messages from the rendered documents.

See:
https://yihui.org/knitr/demo/output/
https://github.com/Mouse-Imaging-Centre/RMINC/issues/218

**Comment by michaeldumelle** [comment]
@sagesteppe thanks for the kind words and for the suggestion. Your suggestion will be implemented in the next version of spsurvey submitted to CRAN (the current version of spsurvey is v5.4.1).

**Comment by michaeldumelle** [comment]
@sagesteppe this suggestion has been pushed to CRAN as part of v5.5.0.
