### ISSUE TITLE
Feature Request Wilson Score Interval in Cat Analysis

### ISSUE THREAD

**Issue by sagesteppe** [USEPA/spsurvey#37]
Hi, 

I was wondering it it was possible for this function to support this? We calculate it using 'confint' in Hmisc, but get slightly different results of the estimate there (I assume due to weighing we use here). I am clearly not a statistician, so apologies if this is very silly.

**Comment by michaeldumelle** [comment]
@sagesteppe thanks for the suggestion. The default variance estimator in spsurvey's analysis functions is a special variance estimator called the local neighborhood variance estimator. The local neighborhood variance estimator incorporates the spatial locations of the sites, with the goal of yielding more precise parameter estimates. It is not immediately clear how the local neighborhood variance estimator could be used to derive an analagous Wilson Score Interval, so this request is not something we will immediately accommodate. If we decide to work on something like this in the future, we will re-open the issue.
