### ISSUE TITLE
Hierarchical addresses

### ISSUE THREAD

**Issue by jasonelaw** [USEPA/spsurvey#4]
In trying to understand the hierarchical addressing, I noticed that

```r
> constructAddr(0, 0, 1, 1, 2)
[1] "11"
> constructAddr(0.1, 0.1, 1, 1, 2)
[1] "14"
```
Even more interesting is:

```r
> constructAddr(3.5, 3.5 , 1, 1, 2)
[1] "11"
```

Is this the desired behavior?

**Comment by tonyolsen** [comment]
First two arguments must be vectors and not single values. The function assumes output from numLevels where the values for contructAddrs are generated.
