### ISSUE TITLE
Apparently not respecting mindist argument

### ISSUE THREAD

**Issue by Grasslandgit** [USEPA/spsurvey#43]
Attempting to sample treated and untreated areas with 1 km min dist between points using the following code:

`n_base <- c(6, 6)
n_base_names <- c("Control", "Treatment")
n_base <- setNames(n_base, n_base_names)
grts.draw <- grts(sframe = sample.frame,
                  n_base = n_base,
                  stratum_var = "Strata",
                  mindis = 1000,
                  maxtry = 50,
                  projcrs_check = T)`

However, I keep getting points that do not meet this criteria returned with no error being thrown. I have confirmed my spatial data are in units of meters and the same projection

**Comment by michaeldumelle** [comment]
Thanks @Grasslandgit ! The `mindis` argument only applies _within_ strata. So, sites in the `"Control"` stratum should be spaced at least 1km apart and sites within the `"Treatment"` stratum should be spaced at least 1km apart, but one site in the `"Control"` stratum may be closer than 1km to a site in the `"Treatment"` stratum. If you the minimum distance requirement is being violated _within_ strata, please provide a [reproducible example](https://forum.posit.co/t/faq-whats-a-reproducible-example-reprex-and-how-do-i-create-one/5219) so we can look into it further.

One approach to consider in your case is to generate some oversample sites (`n_over`) and replace a base site with an oversample that satisfies your distance requirement. Start with the first oversample in the list, and if this does not work, proceed to the next oversample in the list; it is important to the integrity of the design to proceed through the oversample list in **siteID** order.

**Comment by Grasslandgit** [comment]
Ah thank you @michaeldumelle that reassures me at least that there isn't a larger issue going on with the implementation of this. I actually ended up getting around this by creating a repeat loop and taking draws with the break condition being a distance matrix with which the minimum distance requirement is met by all points.
