### ISSUE TITLE
spatial balance metrics

### ISSUE THREAD

**Issue by mgm-cincy-epa** [USEPA/spsurvey#44]
Can spatial balance metrics be calculated for a legacy survey design of monitoring points that was not generated by spsurvey?
Thanks.

**Comment by michaeldumelle** [comment]
@mgm-cincy-epa definitely! If the design has varying inclusion probabilities, make sure to specify the `ip` argument to `sp_balance()`. More is [linked here](https://usepa.github.io/spsurvey/reference/sp_balance.html).
